app/models.py
from app import db
from datetime import datetime
import re
import random

from flask_security import UserMixin, RoleMixin


post_tag = db.Table(
    'post_tag',
    db.Column('post_id', db.Integer, db.ForeignKey('post.id')),
    db.Column('tag_id', db.Integer, db.ForeignKey('tag.id'))
)


def func_slugify(s):
    return s.lower()
    # pattern = r'[^\w+]'
    # slug = re.sub(pattern, '-', s)
    # return slug

    # return s
    # return re.sub(pattern, '-', s.lower())
    # другая реализация логики:
    # return '{0}-{1}'.format(
    #     re.sub(pattern, '-', s.lower()),
    #     str(random.randrange(1, 17))
    # )


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(140))
    slug = db.Column(db.String(140), unique=True)
    tBody = db.Column(db.Text)
    dCreated = db.Column(db.DateTime, default=datetime.now())

    tags = db.relationship(
        'Tag',
        secondary=post_tag,
        backref=db.backref('posts', lazy='dynamic')
    )

    def __init__(self, *args, **kwargs):
        super(Post, self).__init__(*args, **kwargs)
        self.func_generate_slug()

    def func_generate_slug(self):
        if self.title:
            self.slug = func_slugify(self.title)

            # if self.dCreated:
            #     self.slug = func_slugify(self.title.lower()) + '-' + func_slugify(str(self.dCreated))

    def __repr__(self):
        return '{}'.format(self.title)


class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(140))
    slug = db.Column(db.String(140))

    def __init__(self, *args, **kwargs):
        super(Tag, self).__init__(*args, **kwargs)
        self.slug = func_slugify(self.name)

    def __repr__(self):
        return '{}'.format(self.name)


# для flask-security

roles_users = db.Table(
    'roles_users',
    db.Column('id_user', db.Integer(), db.ForeignKey('user.id')),
    db.Column('id_role', db.Integer(), db.ForeignKey('role.id'))
    )


class User(db.Model, UserMixin):
    id = db.Column(db.Integer(), primary_key=True)
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(255))
    name = db.Column(db.String(140))
    date_create = db.Column(db.DateTime, default=datetime.now())
    active = db.Column(db.Boolean())

    roles = db.relationship(
        'Role',
        secondary=roles_users,
        backref=db.backref('users', lazy='dynamic')
        )


class Role(db.Model, RoleMixin):
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(100), unique=True)
    description = db.Column(db.String(255))

app/posts/forms.py
from wtforms import Form, StringField, TextAreaField


class PostForm(Form):
    title = StringField('Название поста:')
    body = TextAreaField('Содержание:')

app/app.py
from flask import Flask
from config import Configuration
from flask_sqlalchemy import SQLAlchemy

from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager

from flask_admin import Admin
from flask_admin.contrib.sqla import ModelView

from flask_security import SQLAlchemyUserDatastore

app = Flask(__name__)
app.config.from_object(Configuration)

db = SQLAlchemy(app)

migrate = Migrate(app, db)
manager = Manager(app)
manager.add_command('db', MigrateCommand)


from models import *
admin = Admin(app)
admin.add_view(ModelView(Post, db.session))
admin.add_view(ModelView(Tag, db.session))

app/main.py
from app import app
from app import db

from posts.blueprint import posts

import view


app.register_blueprint(posts, url_prefix='/blog')

if __name__ == '__main__':
    app.run()

app/posts/blueprint.py
from flask import Blueprint
from flask import render_template

from models import Post, Tag
from .forms import PostForm

from flask import request
from app import db

from flask import redirect
from flask import url_for


posts = Blueprint('posts', __name__, template_folder='templates')


@posts.route('/create', methods=['POST', 'GET'])
def create_post():

    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']

        try:
            post = Post(title=title, body=body)
            db.session.add(post)
            db.session.commit()
        except:
            print('Ошибка при создании поста...')

        return redirect(url_for('posts.index'))

    form = PostForm()
    return render_template('posts/create_post.html', myform=form)


@posts.route('/<slug>/edit/', methods=['POST', 'GET'])
def edit_post(slug):
    post = Post.query.filter(Post.slug == slug).first

    if request.metod == 'POST':
        form = PostForm(formdata=request.form, obj=post)
        form.populate_obj(post)
        db.session.commit()
        return redirect(url_for('posts.mypost', slug=post.slug))

    form = PostForm(obj=post)
    return render_template('posts/edit_post.html', mypost=post, myform=form)



@posts.route('/')
def index():

    q = request.args.get('q')
    if q:
        posts = Post.query.filter(Post.title.contains(q) | Post.tBody.contains(q))
    else:
        posts = Post.query.order_by(Post.dCreated.desc())

    page = request.args.get('page')
    if page and page.isdigit():
        page = int(page)
    else:
        page = 1
    pages = posts.paginate(page=page, per_page=5)

    return render_template('posts/index.html', all_posts=posts, pages=pages)


@posts.route('/<slug>')
def mypost(slug):
    currentPost = Post.query.filter(Post.slug == slug).first()
    tags = currentPost.tags
    return render_template('posts/mypost.html', mypost=currentPost, mytags=tags)


@posts.route('/tag/<slug>')
def mytag(slug):
    currentTag = Tag.query.filter(Tag.slug == slug).first()
    posts = currentTag.posts.all()
    return render_template('posts/mytag.html', mytag=currentTag, allposts=posts)

app/posts/templates/posts/create_post.html
{% extends 'base.html' %}


{% block title %}
    Создание нового поста
{% endblock %}


{% block content_title %}
    <div class="form-group col-sm row">Новый пост:</div>
{% endblock %}


{% block content %}

    <form action="{{ url_for('posts.create_post') }}" method="POST">
        <div class="form-group col-sm row">

        {% for field in myform %}

            {{ field.label() }}
            {{ field(class='form-control', rows='5') }}

        {% endfor %}

        </div>
        <div class="form-group col-sm row">
            <button type="submit" class="btn btn-primary btn-sm">Создать</button>
        </div>
    </form>

{% endblock %}

app/posts/templates/posts/edit_post.html
{% extends 'base.html' %}


{% block title %}
    Редактирование поста
{% endblock %}


{% block content_title %}
    <div class="form-group col-sm row">Пост:</div>
{% endblock %}


{% block content %}

    <form action="{{ url_for('posts.edit_post', slug=mypost.slug) }}" method="POST">
        <div class="form-group col-sm row">

        {% for field in myform %}

            {{ field.label() }}
            {{ field(class='form-control', rows='5') }}

        {% endfor %}

        </div>
        <div class="form-group col-sm row">
            <button type="submit" class="btn btn-primary btn-sm">Изменить</button>
        </div>
    </form>

{% endblock %}

app/posts/templates/posts/index.html
{% extends 'base.html' %}


{% block title %}
    Мои посты
{% endblock %}


{% block content_title %}
    Посмотри, что я запостил:
{% endblock %}


{% block content %}

    {% for p in all_posts %}
        <p>
            <a href="{{ url_for('posts.mypost', slug=p.slug) }}">{{ p.title }}</a>
        </p>
    {% endfor %}

    выводится список постов<br>
    Пост о чем-то важном<br>
    Всякая всячина
<br><br><br>

<!--Пагинация-->
<nav aria-label="Page navigation example">
  <ul class="pagination">
    <li
        {% if not pages.has_prev %}
            class="page-item disabled"
        {% endif %}
    ><a class="page-link" href="./?page={{ pages.prev_num }}">Предыдущая</a></li>

      {% for page in pages.iter_pages() %}
        <li
          {% if page == pages.page %}
            class="page-item active"
          {% endif %}
        ><a class="page-link" href="./?page={{ page }}">{{ page }}
            <span class="sr-only">(current)</span>
        </a></li>
      {% endfor %}

    <li
        {% if not pages.has_next %}
            class="page-item disabled"
        {% endif %}
    ><a class="page-link" href="./?page={{ pages.next_num }}">Следующая</a></li>
  </ul>
</nav>
<!--Пагинация-->

{% endblock %}

app/posts/templates/posts/mypost.html
{% extends 'base.html' %}


{% block title %}
    {{ mypost.title }}
{% endblock %}


{% block content_title %}
    {{ mypost.title }}
{% endblock %}


{% block content %}
    {{ mypost.tBody }}

    <div class="tags">

        {% for t in mytags %}
            <a href="{{ url_for('posts.mytag', slug=t.slug) }}" class="badge badge-primary">{{ t.name }}</a>
        {% endfor %}

    </div>

{% endblock %}

app/posts/templates/posts/mytag.html
{% extends 'base.html' %}


{% block title %}
    Посты с тегом {{ mytag.name }}
{% endblock %}


{% block content_title %}
    Все посты с тегом "{{ mytag.name }}"
{% endblock %}


{% block content %}

    {% for p in allposts %}
        <div class="posts">
            <a href="{{ url_for('posts.mypost', slug=p.slug) }}">{{ p.title }}</a>
        </div>
    {% endfor %}

{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>

        {% block title %}

        {% endblock %} | Проект на Flask

    </title>
</head>
<body>

    <!-- Навигация -->
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <a class="navbar-brand" href=" {{ url_for('index') }} ">V.MAMONTOV</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse"
                  data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                  aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="\admin">Вход в админку</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href=" {{ url_for('posts.index') }} ">Все записи</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Интересное
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">Книги</a>
                        <a class="dropdown-item" href="#">Видео</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Что-то ещё</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Контакты</a>
                </li>
            </ul>


            <form class="form-inline my-2 my-md-0" method="GET">
              <input class="form-control form-control-md mr-sm-2" type="search" placeholder="Введите искомое" aria-label="Search"
                     name="q" value="{{ request.args.get('q', '') }}">
              <button class="btn btn-secondary btn-md my-2 my-sm-0" type="submit">Поиск</button>
            </form>


        </div>
    </nav>
    <!-- Навигация -->

    <div class="container">
        <br>

        <!-- Greeting -->
        <div class="ml-5">
            <h3>
                {% block content_title %}

                {% endblock %}
            </h3>
            <hr>
        </div>



        <!-- Content - это Grid из трёх колонок -->
        <div class="row">
<!--            <div class="col-sm-offset-2 col-sm-8">-->
            <div class="col-sm-8 ml-5">

                {% block content %}

                {% endblock %}

                <hr class="my-4">
            </div>
            <div class="col-xs">
                &nbsp;
                <hr class="my-4">
            </div>

            <div class="col-sm">
                <center>
                    <a href="{{ url_for('posts.create_post') }}"
                       class="btn btn-primary btn-sm" role="button"
                       aria-pressed="true"> + Написать новый пост</a>
                </center>
                <hr class="my-4">
            </div>

        </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>
</body>
</html>

app/templates/index.html
{% extends 'base.html' %}


{% block title %}
    Главная страница
{% endblock %}


{% block content_title %}
    Привет {{ n }}!
{% endblock %}


{% block content %}
    Какой-то текст
{% endblock %}


{% block rightside %}
    <button type="button" class="btn btn-primary btn-sm">Создать новый пост</button>
{% endblock %}